name: CI Pipeline
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Fix and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install @eslint/js eslint-config-airbnb-base eslint-plugin-import globals --save-dev
          
      - name: Run ESLint
        run: npx eslint . --config eslint.config.js --max-warnings=0

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install test dependencies
        run: |
          npm install
          npm install identity-obj-proxy@3.0.0 @jest/globals jest jest-environment-jsdom --save-dev
          
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: --experimental-vm-modules

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
